global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # SkyWalking OAP metrics
  - job_name: 'skywalking-oap'
    static_configs:
      - targets: ['skywalking-oap:1234']
    scrape_interval: 30s
    metrics_path: /metrics

  # Prometheus self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Adam test application metrics (if available)
  - job_name: 'adam-test-app'
    static_configs:
      - targets: ['adam-test-app:8081']
    scrape_interval: 30s
    metrics_path: /actuator/prometheus 