redis:
  sdk:
    config:
      host: "localhost"  # Redis 服务器地址
      port: 6379         # Redis 服务端口
      poolSize: 64       # 连接池大小
      minIdleSize: 10    # 最小空闲连接数
      idleTimeout: 10000 # 空闲连接超时
      connectTimeout: 10000 # 连接超时时间
      retryAttempts: 3   # 重试次数
      retryInterval: 1000 # 重试间隔
      pingInterval: 30000 # 心跳检测间隔
      keepAlive: true    # 启用TCP保活

